env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod tidy
builds:
- ldflags:
    - -s -w
    - -X 'github.com/carlosjgp/kubernetes-config-collector/pkg/cmd.version={{.Version}}'
    - -X 'github.com/carlosjgp/kubernetes-config-collector/pkg/cmd.commit={{.Commit}}'
    - -X 'github.com/carlosjgp/kubernetes-config-collector/pkg/cmd.date={{.Date}}'
    - -X 'github.com/carlosjgp/kubernetes-config-collector/pkg/cmd.builtBy=Carlos Juan Gómez Peñalver'
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ .Tag }}-next"
