language: go

git:
  quiet: true

services: docker

go:
  - 1.13.x

addons:
  apt:
    update: true
    packages:
      - python3

before_install:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./go-test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
